### ISSUE TITLE
Plugin funktioniert nicht mehr

### ISSUE THREAD

**Issue by the-unknown** [Maven85/plugin.video.7tv-webapi#3]
Hey,

leider funktioniert das Plugin nicht mehr.
In der kodi.log steht folgender Fehler:

```
14:17:34.594 T:1103069952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.7tv-webapi/default.py", line 44, in <module>
                                                nav.listVideos(params.get('path'), params.get('channel_id', None), params.get('tvshow_id'), params.get('video_type'), int(params.get('page')))
                                              File "/home/osmc/.kodi/addons/plugin.video.7tv-webapi/resources/lib/navigation.py", line 273, in listVideos
                                                infoLabels = getInfoLabel(item, 'video', channel_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.7tv-webapi/resources/lib/navigation.py", line 351, in getInfoLabel
                                                info['season'] = int(re.compile('Staffel ([0-9]+)', re.DOTALL).findall(item_data.get('titles').get('default'))[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
14:17:34.983 T:1925452368   ERROR: GetDirectory - Error getting plugin://plugin.video.7tv-webapi/?eyJhY3Rpb24iOiAibGlzdFZpZGVvcyIsICJwYXRoIjogIi92aWRlb3MiLCAidHZzaG93X2lkIjogIjEwMDAxNDQiLCAicGFnZSI6IDAsICJ2aWRlb190eXBlIjogIkNsaXBzIn0
14:17:34.985 T:1925452368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.7tv-webapi/?eyJhY3Rpb24iOiAibGlzdFZpZGVvcyIsICJwYXRoIjogIi92aWRlb3MiLCAidHZzaG93X2lkIjogIjEwMDAxNDQiLCAicGFnZSI6IDAsICJ2aWRlb190eXBlIjogIkNsaXBzIn0) failed
```

**Comment by Maven85** [comment]
Grundsätzlich funktioniert das Plugin.

Was hast du denn versucht aufzurufen?

**Comment by the-unknown** [comment]
Ich habe mir das Repository als zip (master.zip) auf meinen RasPi gezogen und in Kodi über "aus Zip-Archiv installieren" installiert. Hat auch funktioniert und das Plugin lief an.

Dann wollte ich auf die Mediathek von ProSieben zugreifen. Mein Weg war:
Beliebte Sendungen --> Das Ding Des Jahres --> Ganze Folgen 
Ab da wird nichts mehr angezeigt und in der kodi.log findet sich der Fehler von oben.

**Comment by Maven85** [comment]
Kann ich zwar nicht nachstellen, werde ich morgen aber beheben.

Wäre nett, wenn du das dann mal testen könntest.

**Comment by ghost** [comment]
Sieht so aus als ob zu https://magellan-api.p7s1.io seitens der Sender migriert wird.
Wenn zum Beispiel die Serie Hawaii Five-0 ausgewählt wird sind keine Folgen mehr zu sehen,
auf der Webseite von Sat1 aber schon.
Ich habe relativ wenig Erfahrung mit webscrapping aber wenn ich irgendwie von Hilfe sein kann, tue ich
es auch.

**Comment by Maven85** [comment]
Da die Inhalte von der 7TV-API geliefert wird, kann ich leider nichts machen.
Müssen wir mal abwarten, wie sich das entwickelt.

Das eigentlich gemeldete Problem sollte jetzt behoben sein.
